---
title: "Data Visualisation: Notes and Exercises"
author: "Nathan W. Van Bibber"
date: "9/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## First Steps

```{r}
library(tidyverse)

ggplot(data = mpg) +
    geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
x <- "hello"
```

Make a scatter plot of `hwy` vs `cyl`
```{r}
ggplot(data = mpg) +
    geom_point(mapping = aes(x = hwy, y = cyl))
```

```{r}
ggplot(mpg) +
    geom_point(aes(class, drv))
```

```{r}
two_seater <- mpg %>% 
    filter(class == "2seater")
two_seater

```

```{r}
ggplot(data = two_seater) +
    geom_point(mapping = aes(x = displ, y = hwy), data = mpg) +
    geom_point(mapping = aes(x = displ, y = hwy, color = class), shape = 17, size = 2)
```

## Facets

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ .)
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
```


### Exercise 3.6.1-6

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(mapping = aes(group = drv),se = FALSE)
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color = drv)) + 
  geom_smooth(se = FALSE)
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color = drv)) + 
  geom_smooth(mapping = aes(linetype = drv),se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(fill = drv, stroke = 2), shape = 21, size = 4, color = 'white')
  
```


